//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courses.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Courses.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcija.
        /// </summary>
        public static string Akcija {
            get {
                return ResourceManager.GetString("Akcija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Dodaj {
            get {
                return ResourceManager.GetString("Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje države.
        /// </summary>
        public static string DodavanjeDrzave {
            get {
                return ResourceManager.GetString("DodavanjeDrzave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Države.
        /// </summary>
        public static string Drzave {
            get {
                return ResourceManager.GetString("Drzave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edukatori.
        /// </summary>
        public static string Edukatori {
            get {
                return ResourceManager.GetString("Edukatori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradovi.
        /// </summary>
        public static string Gradovi {
            get {
                return ResourceManager.GetString("Gradovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni.
        /// </summary>
        public static string Izmijeni {
            get {
                return ResourceManager.GetString("Izmijeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena države.
        /// </summary>
        public static string IzmjenaDrzave {
            get {
                return ResourceManager.GetString("IzmjenaDrzave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolna ploča.
        /// </summary>
        public static string KontrolnaPloca {
            get {
                return ResourceManager.GetString("KontrolnaPloca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnici.
        /// </summary>
        public static string Korisnici {
            get {
                return ResourceManager.GetString("Korisnici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string KorisnickoIme {
            get {
                return ResourceManager.GetString("KorisnickoIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursevi.
        /// </summary>
        public static string Kursevi {
            get {
                return ResourceManager.GetString("Kursevi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Lozinka {
            get {
                return ResourceManager.GetString("Lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Naziv {
            get {
                return ResourceManager.GetString("Naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string NazivAplikacije {
            get {
                return ResourceManager.GetString("NazivAplikacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema država za prikaz..
        /// </summary>
        public static string NemaDrzava {
            get {
                return ResourceManager.GetString("NemaDrzava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavijesti.
        /// </summary>
        public static string Obavijesti {
            get {
                return ResourceManager.GetString("Obavijesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblasti.
        /// </summary>
        public static string Oblasti {
            get {
                return ResourceManager.GetString("Oblasti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string Obrisi {
            get {
                return ResourceManager.GetString("Obrisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava.
        /// </summary>
        public static string Odjava {
            get {
                return ResourceManager.GetString("Odjava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polaznici.
        /// </summary>
        public static string Polaznici {
            get {
                return ResourceManager.GetString("Polaznici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozdrav.
        /// </summary>
        public static string Pozdrav {
            get {
                return ResourceManager.GetString("Pozdrav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string Prijava {
            get {
                return ResourceManager.GetString("Prijava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavite se na Courses.
        /// </summary>
        public static string PrijaviteSe {
            get {
                return ResourceManager.GetString("PrijaviteSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string Spremi {
            get {
                return ResourceManager.GetString("Spremi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipovi obavijesti.
        /// </summary>
        public static string TipoviObavijesti {
            get {
                return ResourceManager.GetString("TipoviObavijesti", resourceCulture);
            }
        }
    }
}
